FROM php:8.3

ENV TZ=America/Sao_Paulo
ENV PHP_IDE_CONFIG="serverName=local"

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
      tzdata \
      pkg-config \
      unzip \
      default-mysql-server \
      netcat-openbsd

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get install -y --no-install-recommends libonig-dev
RUN docker-php-ext-install mbstring

RUN apt-get install -y --no-install-recommends libzip-dev
RUN docker-php-ext-install zip

RUN docker-php-ext-install mysqli pdo_mysql
RUN docker-php-ext-install bcmath
RUN docker-php-ext-install sockets

RUN pecl install xdebug
RUN docker-php-ext-enable xdebug   

RUN usermod -d /var/lib/mysql mysql

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /laravel-replicador
